# Generated by Django 3.1.7 on 2021-03-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20210318_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.ManyToManyField(to='bookstore.Tag'),
        ),
    ]
